import type { QuizDefinition } from '../schema';

export const charmeQuiz: QuizDefinition = {
  id: 'quiz.charme.v1',
  title: 'The Art of Charm',
  titleDe: 'Die Kunst des Charmes',
  subtitle: 'Discover your unique signature of attraction',
  subtitleDe: 'Entdecke deine einzigartige Signatur der Anziehung',
  emoji: '\u2728',
  accentColor: '#D4AF37',
  scoringModel: 'multi-dimension',
  dimensions: ['warmth', 'resonance', 'authenticity', 'presence'],
  questions: [
    {
      id: 'q1',
      text: 'Du betrittst einen Raum voller Fremder. Wie orientierst du dich?',
      context: 'Der erste Eindruck',
      options: [
        { id: 'q1a', text: 'Ich scanne nach bekannten Gesichtern \u2013 und wenn ich keins finde, warte ich, bis jemand mich anspricht.', scores: { warmth: 2, resonance: 4, authenticity: 4, presence: 4 } },
        { id: 'q1b', text: 'Ich suche die Person, die am unsichersten wirkt, und gehe direkt auf sie zu.', scores: { warmth: 5, resonance: 4, authenticity: 5, presence: 5 } },
        { id: 'q1c', text: 'Ich positioniere mich strategisch gut sichtbar und beginne ein angeregtes Gespr\u00e4ch mit dem N\u00e4chstbesten.', scores: { warmth: 3, resonance: 2, authenticity: 2, presence: 1 } },
        { id: 'q1d', text: 'Ich beobachte die Dynamik des Raums \u2013 wer geh\u00f6rt zusammen, wo ist Energie, wo Spannung?', scores: { warmth: 3, resonance: 5, authenticity: 4, presence: 3 } },
      ],
    },
    {
      id: 'q2',
      text: 'Jemand erz\u00e4hlt dir einen Witz, der nicht besonders lustig ist. Was passiert in deinem Gesicht?',
      context: 'Das Geheimnis des L\u00e4chelns',
      options: [
        { id: 'q2a', text: 'Ich lache h\u00f6flich mit \u2013 niemand sollte sich unwohl f\u00fchlen.', scores: { warmth: 4, resonance: 3, authenticity: 2, presence: 4 } },
        { id: 'q2b', text: 'Meine Mundwinkel heben sich, aber meine Augen verraten mich \u2013 ich kann nicht l\u00fcgen.', scores: { warmth: 3, resonance: 4, authenticity: 5, presence: 3 } },
        { id: 'q2c', text: "Ich schmunzle warm und sage: 'Das war charmant versucht.'", scores: { warmth: 5, resonance: 3, authenticity: 4, presence: 4 } },
        { id: 'q2d', text: 'Ich strahle W\u00e4rme aus und lenke geschickt auf etwas um, bei dem wir beide wirklich lachen k\u00f6nnen.', scores: { warmth: 5, resonance: 2, authenticity: 3, presence: 2 } },
      ],
    },
    {
      id: 'q3',
      text: 'Jemand erz\u00e4hlt dir von einem Problem, das dich pers\u00f6nlich nicht betrifft. Wie h\u00f6rst du zu?',
      context: 'Die Kunst des Zuh\u00f6rens',
      options: [
        { id: 'q3a', text: 'Ich stelle gezielte Fragen, um die Situation zu analysieren und L\u00f6sungen anzubieten.', scores: { warmth: 3, resonance: 1, authenticity: 3, presence: 2 } },
        { id: 'q3b', text: 'Ich lehne mich vor, halte Blickkontakt und lasse die Stille wirken, wenn sie n\u00f6tig ist.', scores: { warmth: 5, resonance: 5, authenticity: 5, presence: 5 } },
        { id: 'q3c', text: 'Ich teile \u00e4hnliche eigene Erfahrungen, damit die Person sich weniger allein f\u00fchlt.', scores: { warmth: 4, resonance: 2, authenticity: 4, presence: 2 } },
        { id: 'q3d', text: 'Ich nicke, fasse zusammen und zeige durch meine K\u00f6rpersprache, dass ich pr\u00e4sent bin.', scores: { warmth: 4, resonance: 4, authenticity: 3, presence: 4 } },
      ],
    },
    {
      id: 'q4',
      text: 'Ein Streit entwickelt sich zwischen zwei Menschen in deiner Gegenwart. Was tust du?',
      context: 'Spannung im Raum',
      options: [
        { id: 'q4a', text: 'Ich bringe Humor ein \u2013 ein gut getimter Kommentar kann Wunder wirken.', scores: { warmth: 4, resonance: 2, authenticity: 3, presence: 1 } },
        { id: 'q4b', text: 'Ich wende mich an die ruhigere Person und gebe ihr Raum, ihre Perspektive zu teilen.', scores: { warmth: 5, resonance: 4, authenticity: 4, presence: 5 } },
        { id: 'q4c', text: 'Ich bleibe gelassen und strahle eine Ruhe aus, die ansteckend wirkt.', scores: { warmth: 4, resonance: 5, authenticity: 4, presence: 5 } },
        { id: 'q4d', text: 'Ich strukturiere das Gespr\u00e4ch und schlage einen diplomatischen Kompromiss vor.', scores: { warmth: 3, resonance: 1, authenticity: 3, presence: 3 } },
      ],
    },
    {
      id: 'q5',
      text: 'Du hast einen Fehler gemacht, der anderen aufgefallen ist. Wie gehst du damit um?',
      context: 'Der verletzliche Moment',
      options: [
        { id: 'q5a', text: 'Ich gebe es offen zu und lache \u00fcber mich selbst \u2013 Perfektion langweilt sowieso.', scores: { warmth: 4, resonance: 3, authenticity: 5, presence: 2 } },
        { id: 'q5b', text: 'Ich entschuldige mich aufrichtig und frage, wie ich es wieder gutmachen kann.', scores: { warmth: 5, resonance: 3, authenticity: 5, presence: 4 } },
        { id: 'q5c', text: 'Ich erkl\u00e4re den Kontext meines Fehlers, damit andere ihn einordnen k\u00f6nnen.', scores: { warmth: 2, resonance: 1, authenticity: 3, presence: 2 } },
        { id: 'q5d', text: 'Ich zeige kurz Betroffenheit, aber wechsle schnell zu einer L\u00f6sung.', scores: { warmth: 3, resonance: 2, authenticity: 2, presence: 2 } },
      ],
    },
    {
      id: 'q6',
      text: 'Du willst jemandem ehrlich sagen, was du an ihm sch\u00e4tzt. Wie machst du das?',
      context: 'Das Kompliment',
      options: [
        { id: 'q6a', text: "Ich sage es direkt und spezifisch: 'Was du gerade gemacht hast, war brillant, weil...'", scores: { warmth: 4, resonance: 1, authenticity: 4, presence: 2 } },
        { id: 'q6b', text: 'Ich lege meine Hand auf ihre Schulter und sage es mit warmem Blick in wenigen Worten.', scores: { warmth: 5, resonance: 5, authenticity: 4, presence: 4 } },
        { id: 'q6c', text: 'Ich erw\u00e4hne es sp\u00e4ter nebenbei, fast beil\u00e4ufig \u2013 gro\u00dfe Gesten machen mich verlegen.', scores: { warmth: 3, resonance: 4, authenticity: 5, presence: 4 } },
        { id: 'q6d', text: 'Ich finde einen spielerischen Weg, es in einen Insider-Witz zwischen uns zu verwandeln.', scores: { warmth: 4, resonance: 2, authenticity: 3, presence: 1 } },
      ],
    },
    {
      id: 'q7',
      text: 'Du sitzt neben jemandem, den du nicht kennst, aber die Situation erlaubt Gespr\u00e4ch. Was passiert?',
      context: 'Der Fremde neben dir',
      options: [
        { id: 'q7a', text: 'Ich warte auf einen nat\u00fcrlichen Moment \u2013 vielleicht ein geteiltes Schmunzeln \u00fcber etwas.', scores: { warmth: 4, resonance: 5, authenticity: 5, presence: 4 } },
        { id: 'q7b', text: 'Ich starte mit einer offenen Frage, die echte Neugier zeigt.', scores: { warmth: 5, resonance: 2, authenticity: 4, presence: 2 } },
        { id: 'q7c', text: 'Ich bleibe still, aber sende offene K\u00f6rpersprache \u2013 wer reden will, wird es tun.', scores: { warmth: 3, resonance: 5, authenticity: 4, presence: 5 } },
        { id: 'q7d', text: 'Ich kommentiere etwas Konkretes um uns herum, um das Eis zu brechen.', scores: { warmth: 4, resonance: 2, authenticity: 3, presence: 2 } },
      ],
    },
    {
      id: 'q8',
      text: 'Ein Freund hat einen schlechten Tag. Du merkst es an seiner Energie. Was ist deine erste Reaktion?',
      context: 'Der schwere Tag',
      options: [
        { id: 'q8a', text: "Ich frage direkt: 'Was ist los?' \u2013 Ehrlichkeit \u00fcber allem.", scores: { warmth: 4, resonance: 2, authenticity: 4, presence: 2 } },
        { id: 'q8b', text: 'Ich sitze einfach neben ihm und bin da \u2013 Worte kommen, wenn sie kommen.', scores: { warmth: 5, resonance: 5, authenticity: 5, presence: 5 } },
        { id: 'q8c', text: "Ich bringe ihm seinen Lieblingskaffee und sage: 'Du musst nichts erz\u00e4hlen.'", scores: { warmth: 5, resonance: 4, authenticity: 4, presence: 5 } },
        { id: 'q8d', text: 'Ich versuche, ihn abzulenken \u2013 manchmal braucht man einfach Pause vom Gr\u00fcbeln.', scores: { warmth: 4, resonance: 2, authenticity: 3, presence: 1 } },
      ],
    },
    {
      id: 'q9',
      text: 'Du stehst im Mittelpunkt \u2013 alle Augen auf dir. Was ist dein Instinkt?',
      context: 'Im Rampenlicht',
      options: [
        { id: 'q9a', text: 'Ich genie\u00dfe es kurz, aber lenke dann schnell den Fokus auf andere.', scores: { warmth: 5, resonance: 3, authenticity: 4, presence: 3 } },
        { id: 'q9b', text: 'Ich nutze den Moment, um etwas Bedeutungsvolles zu sagen.', scores: { warmth: 3, resonance: 1, authenticity: 4, presence: 2 } },
        { id: 'q9c', text: 'Ich mache etwas \u00dcberraschendes, das Spannung bricht und alle einbezieht.', scores: { warmth: 4, resonance: 2, authenticity: 3, presence: 1 } },
        { id: 'q9d', text: 'Ich halte den Moment still, l\u00e4chle und lasse meine Ruhe sprechen.', scores: { warmth: 3, resonance: 5, authenticity: 4, presence: 5 } },
      ],
    },
    {
      id: 'q10',
      text: 'Du merkst, dass jemand in der Gruppe sich unwohl f\u00fchlt. Was tust du?',
      context: 'Die unsichtbare Verbindung',
      options: [
        { id: 'q10a', text: 'Ich gehe diskret zu ihm und frage leise, ob alles okay ist.', scores: { warmth: 5, resonance: 4, authenticity: 5, presence: 5 } },
        { id: 'q10b', text: 'Ich beziehe ihn geschickt ins Gespr\u00e4ch ein, ohne es auff\u00e4llig zu machen.', scores: { warmth: 5, resonance: 3, authenticity: 3, presence: 3 } },
        { id: 'q10c', text: 'Ich bleibe in seiner N\u00e4he und gebe ihm durch meine Pr\u00e4senz Sicherheit.', scores: { warmth: 4, resonance: 5, authenticity: 4, presence: 5 } },
        { id: 'q10d', text: 'Ich spreche ihn sp\u00e4ter unter vier Augen an \u2013 \u00f6ffentlich k\u00f6nnte es ihm unangenehm sein.', scores: { warmth: 4, resonance: 3, authenticity: 4, presence: 4 } },
      ],
    },
    {
      id: 'q11',
      text: 'Eine Unterhaltung nimmt eine tiefe Wendung. Wie reagierst du auf emotionale Offenheit?',
      context: 'Worte und Stille',
      options: [
        { id: 'q11a', text: 'Ich teile eine eigene verletzliche Geschichte, um Gleichheit zu schaffen.', scores: { warmth: 4, resonance: 3, authenticity: 5, presence: 2 } },
        { id: 'q11b', text: 'Ich halte den Raum in Stille \u2013 manchmal ist Pr\u00e4senz mehr als Worte.', scores: { warmth: 4, resonance: 5, authenticity: 4, presence: 5 } },
        { id: 'q11c', text: "Ich dr\u00fccke in Worten aus, was ich f\u00fchle: 'Das ber\u00fchrt mich sehr.'", scores: { warmth: 5, resonance: 2, authenticity: 5, presence: 3 } },
        { id: 'q11d', text: 'Ich frage behutsam weiter, um der Tiefe Raum zu geben.', scores: { warmth: 5, resonance: 3, authenticity: 4, presence: 4 } },
      ],
    },
    {
      id: 'q12',
      text: 'Du verl\u00e4sst einen Raum. Was sollen die Menschen \u00fcber dich denken?',
      context: 'Der Abschied',
      options: [
        { id: 'q12a', text: "'Mit ihr war es nie langweilig \u2013 sie hat Energie gebracht.'", scores: { warmth: 3, resonance: 2, authenticity: 3, presence: 1 } },
        { id: 'q12b', text: "'In ihrer N\u00e4he habe ich mich wohler gef\u00fchlt.'", scores: { warmth: 5, resonance: 5, authenticity: 4, presence: 5 } },
        { id: 'q12c', text: "'Sie hat mich wirklich gesehen und verstanden.'", scores: { warmth: 5, resonance: 4, authenticity: 5, presence: 4 } },
        { id: 'q12d', text: "'Sie ist klug und charmant \u2013 ich w\u00fcrde gern mehr Zeit mit ihr verbringen.'", scores: { warmth: 4, resonance: 2, authenticity: 3, presence: 2 } },
      ],
    },
  ],
  profiles: [
    {
      id: 'herzoffner',
      title: 'Der Herz\u00f6ffner',
      emoji: '\ud83d\udc96',
      color: '#D2A95A',
      description: 'Du bist das menschliche \u00c4quivalent eines offenen Kaminfeuers. Menschen entspannen sich in deiner Gegenwart, oft ohne zu wissen warum. Dein Geheimnis? Du machst nichts \u2013 du bist einfach. Deine Augen lachen mit, wenn dein Mund l\u00e4chelt. Du h\u00f6rst nicht nur zu, du h\u00f6rst hinein.',
      thresholds: { warmth: 4.2, resonance: 4.2, authenticity: 4.2, presence: 4.2 },
      priority: 1,
    },
    {
      id: 'magnetische',
      title: 'Die Magnetische',
      emoji: '\u26a1',
      color: '#E8C87A',
      description: 'Du bist der seltene Fall, in dem Charisma und Charme sich die Waage halten. Menschen bemerken dich, wenn du einen Raum betrittst \u2013 aber nicht, weil du Aufmerksamkeit suchst, sondern weil deine Energie ansteckend ist.',
      thresholds: { warmth: 3.5 },
      priority: 2,
    },
    {
      id: 'stiller-verzauberer',
      title: 'Der Stille Verzauberer',
      emoji: '\ud83c\udf19',
      color: '#8FB8A8',
      description: 'Du brauchst keine Worte, um zu verzaubern. Ein Blick von dir sagt mehr als die Monologe anderer. Dein Charme entfaltet sich nicht durch das, was du tust, sondern durch das, was du nicht tust.',
      thresholds: { resonance: 4, authenticity: 4, presence: 3.5 },
      priority: 3,
    },
    {
      id: 'diplomat',
      title: 'Der Diplomat',
      emoji: '\ud83c\udf09',
      color: '#5B8A9A',
      description: 'Dein Charme ist ein Werkzeug der Verbindung. Du siehst, wo Br\u00fccken fehlen, und baust sie \u2013 elegant, diskret, ohne dass jemand merkt, dass du der Architekt warst.',
      thresholds: { warmth: 3, presence: 3.5 },
      priority: 4,
    },
    {
      id: 'esprit-funke',
      title: 'Der Esprit-Funke',
      emoji: '\u2728',
      color: '#E8C87A',
      description: 'Dein Charme ist eine Waffe \u2013 aber eine, die nie verletzt. Du findest den perfekten Moment f\u00fcr den perfekten Satz. Intellekt und W\u00e4rme sind bei dir untrennbar.',
      thresholds: {},
      priority: 5,
    },
    {
      id: 'praesenz-anker',
      title: 'Der Pr\u00e4senz-Anker',
      emoji: '\u2693',
      color: '#1C5B5C',
      description: 'Du bist der seltene Mensch, bei dem andere automatisch langsamer atmen. Dein Charme wirkt nicht durch Worte oder Taten, sondern durch pure Pr\u00e4senz.',
      thresholds: { presence: 4.5, warmth: 4 },
      priority: 6,
    },
  ],
  resultMapping: {
    markerId: 'quiz.charme.v1',
    profileToTraits: {},
  },
};
