import type { QuizDefinition } from '../schema';

export const eqQuiz: QuizDefinition = {
  id: 'quiz.eq.v1',
  title: 'Your Emotional Signature',
  titleDe: 'Deine Emotionale Signatur',
  subtitle: 'Discover your unique pattern of emotional intelligence',
  subtitleDe: 'Entdecke dein einzigartiges Muster emotionaler Intelligenz',
  emoji: '\ud83d\udd2e',
  accentColor: '#D4AF37',
  scoringModel: 'multi-dimension',
  dimensions: ['perception', 'regulation', 'utilization'],
  questions: [
    {
      id: 'q1',
      text: 'Du wachst mit einem diffusen Unbehagen auf. Kein klarer Grund, nur ein Gef\u00fchl. Was passiert in dir?',
      context: 'Selbstwahrnehmung',
      options: [
        { id: 'q1a', text: 'Ich halte inne und frage mich: Ist das Angst? Traurigkeit? Ersch\u00f6pfung? Ich versuche, das Gef\u00fchl pr\u00e4zise zu benennen.', scores: { perception: 5, regulation: 3, utilization: 2 } },
        { id: 'q1b', text: 'Ich starte meinen Tag und schaue, ob sich das Gef\u00fchl von selbst aufl\u00f6st.', scores: { perception: 1, regulation: 4, utilization: 3 } },
        { id: 'q1c', text: 'Ich nutze das Gef\u00fchl als Signal: Vielleicht sollte ich heute sanfter mit mir sein.', scores: { perception: 3, regulation: 4, utilization: 5 } },
        { id: 'q1d', text: 'Ich spreche sofort mit jemandem dar\u00fcber \u2013 beim Aussprechen wird mir oft klar, was los ist.', scores: { perception: 4, regulation: 2, utilization: 3 } },
      ],
    },
    {
      id: 'q2',
      text: 'Du betrittst einen Raum und sp\u00fcrst sofort: Die Stimmung ist anders als erwartet. Was nimmst du wahr?',
      context: 'Soziale Wahrnehmung',
      options: [
        { id: 'q2a', text: 'Ich registriere subtile Details: verschr\u00e4nkte Arme, gemiedene Blicke, die zu ruhige Stimme.', scores: { perception: 5, regulation: 2, utilization: 3 } },
        { id: 'q2b', text: 'Ich bemerke, dass etwas nicht stimmt, fokussiere mich aber bewusst auf meine eigene Aufgabe.', scores: { perception: 2, regulation: 5, utilization: 2 } },
        { id: 'q2c', text: 'Ich \u00fcberlege strategisch: Wie wirkt sich diese Spannung auf meine Ziele heute aus?', scores: { perception: 3, regulation: 3, utilization: 5 } },
        { id: 'q2d', text: "Ich frage direkt: 'Hey, ist alles okay? Die Stimmung wirkt heute anders.'", scores: { perception: 3, regulation: 1, utilization: 4 } },
      ],
    },
    {
      id: 'q3',
      text: 'Jemand macht eine Bemerkung, die dich trifft. Du sp\u00fcrst, wie \u00c4rger in dir hochsteigt. Was passiert dann?',
      context: 'Impulskontrolle',
      options: [
        { id: 'q3a', text: 'Ich sp\u00fcre den \u00c4rger intensiv, fast k\u00f6rperlich. Ich muss erstmal durchatmen.', scores: { perception: 5, regulation: 3, utilization: 2 } },
        { id: 'q3b', text: 'Ich schalte innerlich einen Gang runter. Ich registriere den \u00c4rger, aber erlaube ihm nicht, meine Reaktion zu diktieren.', scores: { perception: 3, regulation: 5, utilization: 3 } },
        { id: 'q3c', text: 'Ich kontere sofort. Wenn jemand unter die G\u00fcrtellinie geht, darf er wissen, wie das ankommt.', scores: { perception: 3, regulation: 1, utilization: 2 } },
        { id: 'q3d', text: 'Ich frage mich: Will ich jetzt gewinnen oder will ich verstehen?', scores: { perception: 4, regulation: 4, utilization: 5 } },
      ],
    },
    {
      id: 'q4',
      text: "Ein Freund fragt: 'Wie geht's dir?' \u2013 und du merkst, dass 'gut' oder 'schlecht' die Antwort nicht trifft.",
      context: 'Emotionale Granularit\u00e4t',
      options: [
        { id: 'q4a', text: "Ich finde pr\u00e4zise Worte: 'Ich bin melancholisch-nachdenklich, aber nicht traurig.'", scores: { perception: 5, regulation: 2, utilization: 3 } },
        { id: 'q4b', text: "Ich sage 'kompliziert' und lasse es dabei. Nicht jedes Gef\u00fchl braucht ein Label.", scores: { perception: 2, regulation: 4, utilization: 2 } },
        { id: 'q4c', text: "Ich beschreibe es \u00fcber den K\u00f6rper: 'Ich hab so ein Kribbeln im Bauch.'", scores: { perception: 4, regulation: 2, utilization: 2 } },
        { id: 'q4d', text: 'Ich nutze die Frage als Anlass, um mit dem Freund tiefer zu sprechen.', scores: { perception: 3, regulation: 3, utilization: 5 } },
      ],
    },
    {
      id: 'q5',
      text: 'Du musst eine wichtige Pr\u00e4sentation halten. Wie gehst du emotional in diese Situation?',
      context: 'Emotionsnutzung',
      options: [
        { id: 'q5a', text: 'Ich versuche, komplett ruhig zu sein. Nervosit\u00e4t ist der Feind klarer Gedanken.', scores: { perception: 2, regulation: 5, utilization: 2 } },
        { id: 'q5b', text: 'Ich transformiere die Nervosit\u00e4t in Energie. Das Kribbeln ist wie Strom.', scores: { perception: 4, regulation: 3, utilization: 5 } },
        { id: 'q5c', text: 'Ich f\u00fchle alles intensiv \u2013 die Aufregung, die Unsicherheit. Das macht mich authentisch.', scores: { perception: 5, regulation: 1, utilization: 3 } },
        { id: 'q5d', text: 'Ich visualisiere den besten Ausgang und baue mir damit positive Emotionen auf.', scores: { perception: 3, regulation: 4, utilization: 5 } },
      ],
    },
    {
      id: 'q6',
      text: 'Eine Freundin erz\u00e4hlt von einem Problem. Du merkst: Sie will eigentlich nicht deinen Rat.',
      context: 'Empathie',
      options: [
        { id: 'q6a', text: 'Ich sp\u00fcre genau, was sie braucht \u2013 Pr\u00e4senz, nicht L\u00f6sungen. Ich h\u00f6re zu und spiegle ihre Gef\u00fchle.', scores: { perception: 5, regulation: 3, utilization: 4 } },
        { id: 'q6b', text: "Ich frage nach: 'Was brauchst du gerade von mir? Zuh\u00f6ren oder Ideen?'", scores: { perception: 3, regulation: 4, utilization: 5 } },
        { id: 'q6c', text: 'Ich muss aufpassen, dass ich ihre Gef\u00fchle nicht zu stark \u00fcbernehme.', scores: { perception: 5, regulation: 1, utilization: 2 } },
        { id: 'q6d', text: 'Ich gebe trotzdem Rat. Manchmal wissen Menschen nicht, was sie brauchen.', scores: { perception: 2, regulation: 3, utilization: 3 } },
      ],
    },
    {
      id: 'q7',
      text: 'Zwei Menschen, die dir wichtig sind, streiten sich. Du stehst dazwischen.',
      context: 'Konfliktnavigation',
      options: [
        { id: 'q7a', text: 'Ich sp\u00fcre beide Seiten k\u00f6rperlich \u2013 ihre Anspannung, ihre Verletzung.', scores: { perception: 5, regulation: 1, utilization: 2 } },
        { id: 'q7b', text: 'Ich distanziere mich emotional und analysiere: Was ist hier der eigentliche Konflikt?', scores: { perception: 3, regulation: 5, utilization: 4 } },
        { id: 'q7c', text: 'Ich \u00fcberlege, wie ich die Situation de-eskalieren kann.', scores: { perception: 3, regulation: 3, utilization: 5 } },
        { id: 'q7d', text: 'Ich warte ab. Nicht jeder Konflikt braucht meine Intervention.', scores: { perception: 2, regulation: 5, utilization: 3 } },
      ],
    },
    {
      id: 'q8',
      text: 'Deadline-Druck. Zu viel zu tun, zu wenig Zeit. Wie verh\u00e4ltst du dich zu deinem Stresslevel?',
      context: 'Stressreaktion',
      options: [
        { id: 'q8a', text: 'Ich merke es erst, wenn mein K\u00f6rper Alarm schl\u00e4gt \u2013 Kopfschmerzen, Magenprobleme.', scores: { perception: 1, regulation: 2, utilization: 2 } },
        { id: 'q8b', text: "Ich beobachte meinen Stress wie einen Wetterbericht: 'Okay, Sturmwarnung.'", scores: { perception: 4, regulation: 5, utilization: 4 } },
        { id: 'q8c', text: 'Ich nutze den Adrenalinstoß. Unter Druck bin ich fokussierter, schneller.', scores: { perception: 3, regulation: 3, utilization: 5 } },
        { id: 'q8d', text: 'Ich sp\u00fcre den Stress intensiv und teile ihn mit anderen.', scores: { perception: 4, regulation: 2, utilization: 3 } },
      ],
    },
    {
      id: 'q9',
      text: 'Jemand reagiert auf eine harmlose Situation v\u00f6llig \u00fcberzogen. Dein erster Gedanke ist...',
      context: 'Emotionales Verstehen',
      options: [
        { id: 'q9a', text: "'Da steckt mehr dahinter.' Ich frage mich, welche Vorgeschichte das erkl\u00e4rt.", scores: { perception: 5, regulation: 4, utilization: 4 } },
        { id: 'q9b', text: "'Interessant, aber nicht mein Problem.' Ich registriere es, aber lasse mich nicht tangieren.", scores: { perception: 2, regulation: 5, utilization: 2 } },
        { id: 'q9c', text: "'Wie kann ich das nutzen?' Vielleicht offenbart diese Reaktion etwas Wichtiges.", scores: { perception: 3, regulation: 3, utilization: 5 } },
        { id: 'q9d', text: 'Ich bin selbst verunsichert. Starke Emotionen anderer bringen mich aus dem Gleichgewicht.', scores: { perception: 4, regulation: 1, utilization: 1 } },
      ],
    },
    {
      id: 'q10',
      text: 'Dir passiert etwas richtig Gutes \u2013 ein pers\u00f6nlicher Erfolg. Wie gehst du mit dieser Freude um?',
      context: 'Freude teilen',
      options: [
        { id: 'q10a', text: 'Ich koste das Gef\u00fchl aus, verst\u00e4rke es bewusst. Ich erlaube mir, strahlend zu sein.', scores: { perception: 4, regulation: 2, utilization: 5 } },
        { id: 'q10b', text: 'Ich genie\u00dfe es innerlich, bleibe aber nach au\u00dfen gelassen.', scores: { perception: 3, regulation: 5, utilization: 3 } },
        { id: 'q10c', text: 'Ich teile es sofort \u2013 der Wert der Freude verdoppelt sich, wenn sie geteilt wird.', scores: { perception: 4, regulation: 2, utilization: 4 } },
        { id: 'q10d', text: 'Ich analysiere: Was genau hat dieses Gef\u00fchl ausgel\u00f6st? Wie kann ich das replizieren?', scores: { perception: 3, regulation: 4, utilization: 5 } },
      ],
    },
    {
      id: 'q11',
      text: 'Nach einem intensiven Tag merkst du: Dein emotionaler Tank ist leer. Was regeneriert dich?',
      context: 'Emotionale Ersch\u00f6pfung',
      options: [
        { id: 'q11a', text: 'Absolute Stille und Alleinsein. Ich muss das alles erstmal sortieren.', scores: { perception: 5, regulation: 3, utilization: 2 } },
        { id: 'q11b', text: 'Eine klare, ablenkende Aktivit\u00e4t \u2013 Sport, Putzen. Das erdet mich.', scores: { perception: 2, regulation: 5, utilization: 3 } },
        { id: 'q11c', text: 'Ein Wechsel der emotionalen Tonlage: Comedy, Musik, Tanz.', scores: { perception: 3, regulation: 4, utilization: 5 } },
        { id: 'q11d', text: 'Mehr Verbindung, aber anders: Ich rufe jemanden an, der mich aufl\u00e4dt.', scores: { perception: 4, regulation: 2, utilization: 4 } },
      ],
    },
    {
      id: 'q12',
      text: 'Wenn du an dein Verh\u00e4ltnis zu Emotionen denkst \u2013 wie w\u00fcrdest du es beschreiben?',
      context: 'Integration',
      options: [
        { id: 'q12a', text: 'Intensiv und immersiv. Ich f\u00fchle alles \u2013 meins, deins, das des Raumes.', scores: { perception: 5, regulation: 1, utilization: 3 } },
        { id: 'q12b', text: 'Kontrolliert und bewusst. Ich beobachte meine Emotionen, aber sie steuern mich nicht.', scores: { perception: 3, regulation: 5, utilization: 4 } },
        { id: 'q12c', text: 'Strategisch und adaptive. Emotionen sind Daten und Werkzeuge.', scores: { perception: 3, regulation: 4, utilization: 5 } },
        { id: 'q12d', text: 'Ehrlich gesagt: kompliziert. Manchmal \u00fcberw\u00e4ltigt, manchmal taub.', scores: { perception: 3, regulation: 2, utilization: 2 } },
      ],
    },
  ],
  profiles: [
    {
      id: 'resonator',
      title: 'Der Resonator',
      emoji: '\ud83c\udfad',
      color: '#4A0E4E',
      description: 'Du bist ein emotionaler Seismograph \u2013 fein kalibriert f\u00fcr die subtilen Schwingungen, die andere gar nicht registrieren. Noch bevor jemand spricht, hast du die Atmosph\u00e4re gelesen.',
      thresholds: { perception: 4 },
      priority: 1,
    },
    {
      id: 'regulator',
      title: 'Der Regulator',
      emoji: '\u2696\ufe0f',
      color: '#1C3B5C',
      description: 'Du bist der emotionale Thermostat \u2013 f\u00e4hig, die Temperatur zu sp\u00fcren und zu justieren, ohne selbst zu \u00fcberhitzen oder einzufrieren.',
      thresholds: { regulation: 4 },
      priority: 2,
    },
    {
      id: 'strategist',
      title: 'Der Stratege',
      emoji: '\ud83c\udfaf',
      color: '#2D4A3E',
      description: 'Du betrachtest Emotionen nicht als Zuf\u00e4lle, sondern als Ressourcen. Nervosit\u00e4t? Transformierst du in fokussierte Energie. \u00c4rger? Kanalisierst du in Durchsetzungskraft.',
      thresholds: { utilization: 4 },
      priority: 3,
    },
    {
      id: 'navigator',
      title: 'Der Navigator',
      emoji: '\ud83e\udded',
      color: '#4A3B2D',
      description: 'Du bist der emotionale Diplomat \u2013 begabt darin, die unsichtbaren Str\u00f6me zwischen Menschen zu lesen und zu navigieren.',
      thresholds: { perception: 3.5, utilization: 3.5 },
      priority: 4,
    },
    {
      id: 'alchemist',
      title: 'Der Alchemist',
      emoji: '\u2697\ufe0f',
      color: '#3D2A4A',
      description: 'Du vereinst, was andere trennen. In dir treffen sich intensive Wahrnehmung, bewusste Steuerung und strategische Nutzung \u2013 eine seltene Integration.',
      thresholds: { perception: 3.5, regulation: 3.5, utilization: 3.5 },
      priority: 5,
    },
    {
      id: 'seeker',
      title: 'Der Suchende',
      emoji: '\ud83d\udd2e',
      color: '#2A2A3D',
      description: 'Du bist ehrlich mit dir: Dein Verh\u00e4ltnis zu Emotionen ist noch in Arbeit. Das ist kein Defizit \u2013 es ist Potenzial.',
      thresholds: {},
      priority: 6,
    },
  ],
  resultMapping: {
    markerId: 'quiz.eq.v1',
    profileToTraits: {},
  },
};
