import type { QuizDefinition } from '../schema';

export const loveLanguagesQuiz: QuizDefinition = {
  id: 'love-languages',
  title: 'What Language Does Your Heart Speak?',
  titleDe: 'Welche Sprache spricht dein Herz?',
  subtitle: 'Discover in 12 questions which lover archetype shapes your being',
  subtitleDe: 'Jeder Mensch gibt und empfaengt Liebe auf eine eigene Art. Entdecke in 12 Fragen, welcher Liebenden-Archetyp dein Wesen praegt.',
  emoji: '❤️',
  accentColor: '#D4AF37',
  scoringModel: 'multi-dimension',
  dimensions: ['touch', 'words', 'time', 'gifts', 'service'],
  questions: [
    {
      id: 'q1',
      text: 'Was tust du instinktiv?',
      context: 'Es ist spaet. Dein Mensch hatte einen schweren Tag.',
      options: [
        { id: 'a', text: 'Ich sage die Worte, die niemand sonst findet', scores: { words: 3 } },
        { id: 'b', text: 'Ich halte einfach still – meine Arme sagen alles', scores: { touch: 3 } },
        { id: 'c', text: 'Ich handle: Tee, Decke, das Handy auf lautlos', scores: { service: 3 } },
        { id: 'd', text: 'Ich bleibe einfach da – meine Praesenz ist das Geschenk', scores: { time: 3 } },
      ],
    },
    {
      id: 'q2',
      text: 'Was siehst du?',
      context: 'Du denkst an einen perfekten Moment mit jemandem, den du liebst.',
      options: [
        { id: 'a', text: 'Ein Gespraech, das die Zeit vergessen laesst', scores: { words: 2, time: 1 } },
        { id: 'b', text: 'Haende, die sich finden, ohne hinzusehen', scores: { touch: 3 } },
        { id: 'c', text: 'Ein Ort, den wir gemeinsam gebaut haben', scores: { service: 2, gifts: 1 } },
        { id: 'd', text: 'Stille, die sich wie Zuhause anfuehlt', scores: { time: 3 } },
      ],
    },
    {
      id: 'q3',
      text: 'Was beruehrt dich am meisten?',
      context: 'Du erhaeltst ein Geschenk von jemandem, der dich liebt.',
      options: [
        { id: 'a', text: 'Die Karte – was jemand schreibt, vergesse ich nie', scores: { words: 3 } },
        { id: 'b', text: 'Die Muehe – dass jemand Zeit investiert hat', scores: { service: 2, time: 1 } },
        { id: 'c', text: 'Das Objekt selbst – ein greifbarer Beweis der Liebe', scores: { gifts: 3 } },
        { id: 'd', text: 'Der Moment des Gebens – die Naehe dabei', scores: { touch: 2, time: 1 } },
      ],
    },
    {
      id: 'q4',
      text: 'Wie reagierst du?',
      context: 'Du spuerst, dass etwas zwischen euch nicht stimmt.',
      options: [
        { id: 'a', text: 'Ich brauche das Gespraech – Ungesagtes brennt', scores: { words: 3 } },
        { id: 'b', text: 'Ich brauche Naehe – Worte koennen luegen, Koerper nicht', scores: { touch: 3 } },
        { id: 'c', text: 'Ich tue etwas – Handeln ist meine Sprache der Versoehnung', scores: { service: 3 } },
        { id: 'd', text: 'Ich brauche Raum – um zu verstehen, was ich fuehle', scores: { time: 2, gifts: 1 } },
      ],
    },
    {
      id: 'q5',
      text: 'Deine ehrlichste Antwort:',
      context: "Jemand fragt: 'Woran erkenne ich, dass du mich liebst?'",
      options: [
        { id: 'a', text: 'An dem, was ich dir sage, wenn niemand zuhoert', scores: { words: 3 } },
        { id: 'b', text: 'Daran, dass ich da bin – auch wenn es unbequem ist', scores: { time: 2, service: 1 } },
        { id: 'c', text: 'An meinen Haenden auf deiner Haut', scores: { touch: 3 } },
        { id: 'd', text: 'Daran, dass ich dich sehe – wirklich sehe', scores: { time: 2, words: 1 } },
      ],
    },
    {
      id: 'q6',
      text: 'Was waehlst du?',
      context: 'Du hast drei Stunden ungestoerte Zeit mit deinem Menschen.',
      options: [
        { id: 'a', text: 'Reden, bis wir vergessen haben, wo wir angefangen haben', scores: { words: 2, time: 1 } },
        { id: 'b', text: 'Nebeneinander existieren – lesen, atmen, sein', scores: { time: 3 } },
        { id: 'c', text: 'Etwas zusammen erschaffen oder erleben', scores: { service: 2, time: 1 } },
        { id: 'd', text: 'Beruehrung ohne Ziel – einfach nah sein', scores: { touch: 3 } },
      ],
    },
    {
      id: 'q7',
      text: 'Welche Wahrheit wuerdest du zugeben?',
      context: 'Ein alter Freund fragt nach deiner groessten Staerke in Beziehungen.',
      options: [
        { id: 'a', text: 'Ich kann Dinge in Worte fassen, die andere nur fuehlen', scores: { words: 3 } },
        { id: 'b', text: 'Ich zeige Liebe durch das, was ich tue, nicht sage', scores: { service: 3 } },
        { id: 'c', text: 'Ich bin physisch praesent in einer Welt voller Ablenkung', scores: { touch: 2, time: 1 } },
        { id: 'd', text: 'Ich gebe Raum – echte Liebe erstickt nicht', scores: { time: 2, gifts: 1 } },
      ],
    },
    {
      id: 'q8',
      text: 'Was hat es verraten?',
      context: 'Du erinnerst dich an den Moment, als du wusstest: Das ist Liebe.',
      options: [
        { id: 'a', text: 'Ein Satz, der alles veraendert hat', scores: { words: 3 } },
        { id: 'b', text: 'Eine Geste, so klein, dass nur ich sie bemerkt habe', scores: { gifts: 2, service: 1 } },
        { id: 'c', text: 'Die Art, wie sich mein Koerper in ihrer Naehe entspannt hat', scores: { touch: 3 } },
        { id: 'd', text: 'Die Stille, die ploetzlich nicht mehr leer war', scores: { time: 3 } },
      ],
    },
    {
      id: 'q9',
      text: 'Welche?',
      context: 'Du musst eine Liebesszene aus einem Film waehlen, die dich am meisten trifft.',
      options: [
        { id: 'a', text: 'Das Gestaendnis – endlich ausgesprochene Wahrheit', scores: { words: 3 } },
        { id: 'b', text: 'Der Kuss im Regen – Koerper sprechen lauter', scores: { touch: 3 } },
        { id: 'c', text: 'Das Opfer – jemand tut das Unmoegliche fuer den anderen', scores: { service: 2, gifts: 1 } },
        { id: 'd', text: 'Der letzte Tanz – Zeit anhalten, nur wir zwei', scores: { time: 3 } },
      ],
    },
    {
      id: 'q10',
      text: 'Was hat am meisten gefehlt?',
      context: 'Dein Herz wurde einmal gebrochen.',
      options: [
        { id: 'a', text: "Die Worte – 'Ich liebe dich' wurde eine Floskel", scores: { words: 3 } },
        { id: 'b', text: 'Die Beruehrung – wir waren Mitbewohner, nicht Liebende', scores: { touch: 3 } },
        { id: 'c', text: 'Die Taten – Versprechen ohne Handlung sind Luegen', scores: { service: 3 } },
        { id: 'd', text: 'Die Zeit – wir hatten keine Stunden mehr fuereinander', scores: { time: 3 } },
      ],
    },
    {
      id: 'q11',
      text: 'Waehle das Bild, das am staerksten resoniert:',
      context: 'Liebe ist fuer dich...',
      options: [
        { id: 'a', text: 'Eine Flamme – sie muss genaehrt werden, oder sie erlischt', scores: { words: 2, touch: 1 } },
        { id: 'b', text: 'Ein Ozean – tief, manchmal stuermisch, immer groesser als ich', scores: { touch: 2, time: 1 } },
        { id: 'c', text: 'Ein Baum – Wurzeln brauchen Zeit, aber dann halten sie', scores: { service: 2, time: 1 } },
        { id: 'd', text: 'Der Wind – man sieht ihn nicht, aber man spuert, wenn er fehlt', scores: { gifts: 2, time: 1 } },
      ],
    },
    {
      id: 'q12',
      text: 'Ich weiss, dass ich geliebt werde, wenn...',
      context: 'Letzte Frage. Vervollstaendige den Satz:',
      options: [
        { id: 'a', text: '...jemand die Worte findet, die ich selbst nicht aussprechen kann', scores: { words: 3 } },
        { id: 'b', text: '...jemand mich beruehrt, als waere ich kostbar', scores: { touch: 3 } },
        { id: 'c', text: '...jemand handelt, bevor ich fragen muss', scores: { service: 3 } },
        { id: 'd', text: '...jemand seine Zeit waehlt, mich zu waehlen', scores: { time: 3 } },
      ],
    },
  ],
  profiles: [
    {
      id: 'the_poet',
      title: 'Der Dichter',
      emoji: '✒️',
      color: '#D4AF37',
      description: 'Du liebst in Saetzen, die andere nie vergessen werden.',
      thresholds: { words: 1 },
      priority: 1,
    },
    {
      id: 'the_flame',
      title: 'Die Flamme',
      emoji: '🔥',
      color: '#C45D4A',
      description: 'Du liebst mit dem ganzen Koerper – Haut spricht lauter als Worte.',
      thresholds: { touch: 1 },
      priority: 2,
    },
    {
      id: 'the_architect',
      title: 'Der Architekt',
      emoji: '🔧',
      color: '#4A90D9',
      description: 'Du baust Liebe mit deinen Haenden, nicht mit Worten.',
      thresholds: { service: 1 },
      priority: 3,
    },
    {
      id: 'the_refuge',
      title: 'Das Refugium',
      emoji: '🏡',
      color: '#6CA192',
      description: 'Deine Praesenz ist das wertvollste Geschenk.',
      thresholds: { time: 1 },
      priority: 4,
    },
    {
      id: 'the_guardian',
      title: 'Der Hueter',
      emoji: '🎁',
      color: '#9B7DB8',
      description: 'Du machst das Unsichtbare greifbar.',
      thresholds: { gifts: 1 },
      priority: 5,
    },
  ],
  resultMapping: {
    markerId: 'quiz.love_languages.v1',
    profileToTraits: {
      the_poet: { 'marker.love.expression': 1.0 },
      the_flame: { 'marker.love.physical_touch': 1.0, 'marker.love.passionate': 0.8 },
      the_architect: { 'marker.love.protective': 1.0 },
      the_refuge: { 'marker.love.togetherness': 1.0 },
      the_guardian: { 'marker.love.sensory_connection': 1.0 },
    },
  },
};
