import type { QuizDefinition } from '../schema';

export const rpgIdentityQuiz: QuizDefinition = {
  id: 'rpg-identity',
  title: 'Which RPG Soul Do You Carry?',
  titleDe: 'Welche Rollenspiel-Seele trägst du in dir?',
  subtitle: 'Discover your hidden class — not who you play, but who you ARE',
  subtitleDe: 'Entdecke deine verborgene Klasse – nicht wer du spielst, sondern wer du BIST',
  emoji: '⚔️',
  accentColor: '#D4AF37',
  scoringModel: 'multi-dimension',
  dimensions: ['d1', 'd2', 'd3'],
  questions: [
    {
      id: 'q1',
      text: 'Was ist dein erster Instinkt?',
      context: 'Du betrittst einen Dungeon. Am Eingang liegt ein verwundeter Fremder.',
      options: [
        { id: 'q1_a', text: 'Ich heile ihn – niemand sollte allein leiden', scores: { d1: 1, d2: 5, d3: 4 } },
        { id: 'q1_b', text: 'Ich frage, wer ihn angegriffen hat – Informationen zuerst', scores: { d1: 2, d2: 3, d3: 3 } },
        { id: 'q1_c', text: 'Ich nehme seine Ausrüstung – er braucht sie nicht mehr', scores: { d1: 4, d2: 1, d3: 1 } },
        { id: 'q1_d', text: 'Ich untersuche die Spuren – der Angreifer könnte noch hier sein', scores: { d1: 3, d2: 2, d3: 5 } },
      ],
    },
    {
      id: 'q2',
      text: 'Wie antwortest du?',
      context: 'Ein mächtiger Drache bietet dir einen Pakt an: Macht gegen einen Teil deiner Erinnerungen.',
      options: [
        { id: 'q2_a', text: 'Ich nehme an – Macht formt die Zukunft, nicht die Vergangenheit', scores: { d1: 5, d2: 1, d3: 2 } },
        { id: 'q2_b', text: 'Ich lehne ab – meine Geschichte macht mich zu dem, was ich bin', scores: { d1: 2, d2: 3, d3: 4 } },
        { id: 'q2_c', text: 'Ich verhandle – welche Erinnerungen genau?', scores: { d1: 3, d2: 2, d3: 3 } },
        { id: 'q2_d', text: 'Ich frage, ob der Pakt auch für meine Gefährten gilt', scores: { d1: 2, d2: 5, d3: 3 } },
      ],
    },
    {
      id: 'q3',
      text: 'Welches Schloss übernimmst du?',
      context: 'Deine Gruppe steht vor einer verschlossenen Tür mit drei Schlössern.',
      options: [
        { id: 'q3_a', text: 'Das Rätselschloss – Logik ist meine Waffe', scores: { d1: 1, d2: 2, d3: 5 } },
        { id: 'q3_b', text: 'Das Kraftschloss – ich breche es auf', scores: { d1: 5, d2: 2, d3: 2 } },
        { id: 'q3_c', text: 'Das magische Siegel – ich spüre seine Frequenz', scores: { d1: 1, d2: 1, d3: 3 } },
        { id: 'q3_d', text: 'Ich halte den anderen den Rücken frei, während sie arbeiten', scores: { d1: 4, d2: 5, d3: 4 } },
      ],
    },
    {
      id: 'q4',
      text: 'Welche wählst du?',
      context: 'Ein Händler bietet dir eine von drei Reliquien an – alle gleich wertvoll.',
      options: [
        { id: 'q4_a', text: 'Die Klinge, die niemals stumpf wird', scores: { d1: 5, d2: 2, d3: 4 } },
        { id: 'q4_b', text: 'Das Amulett, das Gedanken flüstern lässt', scores: { d1: 1, d2: 4, d3: 2 } },
        { id: 'q4_c', text: 'Der Ring, der Schatten zur Tür macht', scores: { d1: 2, d2: 1, d3: 1 } },
        { id: 'q4_d', text: 'Die Laterne, die verborgene Pfade zeigt', scores: { d1: 2, d2: 3, d3: 5 } },
      ],
    },
    {
      id: 'q5',
      text: 'Was tust du?',
      context: 'Dein engster Verbündeter wurde von einem Feind korrumpiert und greift dich an.',
      options: [
        { id: 'q5_a', text: 'Ich kämpfe – wenn es sein muss, töte ich, was ich liebe', scores: { d1: 5, d2: 1, d3: 2 } },
        { id: 'q5_b', text: 'Ich suche den Fluch zu brechen – es muss einen Weg geben', scores: { d1: 1, d2: 4, d3: 4 } },
        { id: 'q5_c', text: 'Ich fliehe und hole Verstärkung – allein schaffe ich das nicht', scores: { d1: 2, d2: 5, d3: 3 } },
        { id: 'q5_d', text: 'Ich lasse mich schlagen – vielleicht weckt es ihn auf', scores: { d1: 1, d2: 5, d3: 1 } },
      ],
    },
    {
      id: 'q6',
      text: 'Wie gehst du damit um?',
      context: 'Du findest ein verbotenes Buch, das dunkle Künste lehrt.',
      options: [
        { id: 'q6_a', text: 'Ich verbrenne es – manche Wissen sollte verloren bleiben', scores: { d1: 4, d2: 3, d3: 5 } },
        { id: 'q6_b', text: 'Ich studiere es heimlich – Wissen ist neutral, nur die Anwendung zählt', scores: { d1: 1, d2: 1, d3: 1 } },
        { id: 'q6_c', text: 'Ich bringe es zu jemandem Weiseren als mir', scores: { d1: 2, d2: 4, d3: 4 } },
        { id: 'q6_d', text: 'Ich verstecke es – falls wir es eines Tages brauchen', scores: { d1: 3, d2: 2, d3: 2 } },
      ],
    },
    {
      id: 'q7',
      text: 'Was denkst du?',
      context: 'Eine Prophezeiung sagt, dass einer aus deiner Gruppe die Welt retten wird.',
      options: [
        { id: 'q7_a', text: 'Ich hoffe, ich bin es – ich bin bereit für diese Last', scores: { d1: 4, d2: 1, d3: 3 } },
        { id: 'q7_b', text: 'Prophezeiungen sind Werkzeuge, keine Wahrheiten', scores: { d1: 2, d2: 2, d3: 1 } },
        { id: 'q7_c', text: 'Egal wer es ist – ich werde denjenigen unterstützen', scores: { d1: 3, d2: 5, d3: 4 } },
        { id: 'q7_d', text: 'Ich analysiere die Prophezeiung auf versteckte Bedeutungen', scores: { d1: 1, d2: 2, d3: 5 } },
      ],
    },
    {
      id: 'q8',
      text: 'Dein Urteil?',
      context: 'Nach einem Sieg hast du die Wahl, was mit dem besiegten Feind geschieht.',
      options: [
        { id: 'q8_a', text: 'Gnade – er hat seine Lektion gelernt', scores: { d1: 2, d2: 4, d3: 3 } },
        { id: 'q8_b', text: 'Gerechtigkeit – das Gesetz soll entscheiden', scores: { d1: 3, d2: 3, d3: 5 } },
        { id: 'q8_c', text: 'Ende – er wird wieder zuschlagen, wenn ich ihn lasse', scores: { d1: 5, d2: 1, d3: 4 } },
        { id: 'q8_d', text: 'Rekrutierung – seine Fähigkeiten könnten nützlich sein', scores: { d1: 2, d2: 4, d3: 1 } },
      ],
    },
    {
      id: 'q9',
      text: 'Wie verbringst du deine Zeit?',
      context: 'Du erhältst Zugang zu einem Ort der Ruhe zwischen den Schlachten.',
      options: [
        { id: 'q9_a', text: 'Training – Stillstand ist Rückschritt', scores: { d1: 5, d2: 1, d3: 4 } },
        { id: 'q9_b', text: 'Meditation – ich höre auf die Stimmen jenseits des Schleiers', scores: { d1: 1, d2: 1, d3: 2 } },
        { id: 'q9_c', text: 'Feiern mit meinen Gefährten – das Leben ist kurz', scores: { d1: 3, d2: 5, d3: 2 } },
        { id: 'q9_d', text: 'Planung – ich kartographiere unseren nächsten Zug', scores: { d1: 2, d2: 3, d3: 5 } },
      ],
    },
    {
      id: 'q10',
      text: 'Nimmst du an?',
      context: 'Ein Geist bietet dir einen Blick in deine Zukunft an.',
      options: [
        { id: 'q10_a', text: 'Ja – Wissen ist Vorbereitung', scores: { d1: 2, d2: 2, d3: 5 } },
        { id: 'q10_b', text: 'Nein – ich schmede mein eigenes Schicksal', scores: { d1: 4, d2: 1, d3: 2 } },
        { id: 'q10_c', text: 'Nur wenn meine Gefährten auch sehen dürfen', scores: { d1: 2, d2: 5, d3: 3 } },
        { id: 'q10_d', text: 'Ich frage den Geist nach seinen Motiven', scores: { d1: 1, d2: 2, d3: 4 } },
      ],
    },
    {
      id: 'q11',
      text: 'Dein nächster Schritt?',
      context: 'Du entdeckst, dass ein Mitglied deiner Gruppe ein Spion ist.',
      options: [
        { id: 'q11_a', text: 'Konfrontation – Verrat verdient sofortige Antwort', scores: { d1: 5, d2: 2, d3: 4 } },
        { id: 'q11_b', text: 'Falsche Informationen füttern – ich nutze den Spion gegen seine Meister', scores: { d1: 2, d2: 1, d3: 1 } },
        { id: 'q11_c', text: 'Die Gruppe informieren – gemeinsam entscheiden wir', scores: { d1: 3, d2: 5, d3: 4 } },
        { id: 'q11_d', text: 'Verstehen, warum – vielleicht gibt es einen tieferen Grund', scores: { d1: 1, d2: 4, d3: 2 } },
      ],
    },
    {
      id: 'q12',
      text: 'Wofür hast du all das getan?',
      context: 'Am Ende deiner Reise steht eine letzte Wahl: Macht, die die Welt verändert – oder Frieden, der sie heilt.',
      options: [
        { id: 'q12_a', text: 'Macht – nur wer Macht hat, kann schützen, was ihm lieb ist', scores: { d1: 5, d2: 1, d3: 3 } },
        { id: 'q12_b', text: 'Frieden – genug Blut ist geflossen', scores: { d1: 1, d2: 4, d3: 4 } },
        { id: 'q12_c', text: 'Weder noch – ich gehe meinen eigenen Weg', scores: { d1: 3, d2: 1, d3: 1 } },
        { id: 'q12_d', text: 'Für meine Gefährten – sie sollen entscheiden', scores: { d1: 2, d2: 5, d3: 3 } },
      ],
    },
  ],
  profiles: [
    {
      id: 'paladin',
      title: 'DER SCHWERTTRÄGER DES LICHTS',
      emoji: '🗡️',
      color: '#D4AF37',
      description: 'Du trägst das Gewicht der Welt – und weißt, dass es deine Bestimmung ist.',
      thresholds: { d1: 0.6, d2: 0.5, d3: 0.6 },
      priority: 1,
    },
    {
      id: 'nekromant',
      title: 'DER WANDERER ZWISCHEN DEN SCHLEIERN',
      emoji: '💀',
      color: '#6B4C9A',
      description: 'Du siehst, was andere fürchten – und findest darin Wahrheit.',
      thresholds: { d1: -0.4, d2: -0.4, d3: -0.4 },
      priority: 2,
    },
    {
      id: 'heiler',
      title: 'DIE QUELLE DER STILLE',
      emoji: '🌿',
      color: '#6CA192',
      description: 'Deine Stärke liegt nicht im Kämpfen – sondern im Wieder-Ganz-Machen.',
      thresholds: { d1: -0.5, d2: 0.6 },
      priority: 3,
    },
    {
      id: 'berserker',
      title: 'DIE FLAMME, DIE NICHT ERLISCHT',
      emoji: '🔥',
      color: '#C45D4A',
      description: 'Du lebst laut, liebst laut, kämpfst laut – und entschuldigst dich für nichts davon.',
      thresholds: { d1: 0.65, d2: -0.4 },
      priority: 4,
    },
    {
      id: 'stratege',
      title: 'DER ARCHITEKT DER MÖGLICHKEITEN',
      emoji: '🎯',
      color: '#4A90D9',
      description: 'Du siehst Schachzüge, wo andere nur Chaos sehen.',
      thresholds: { d3: 0.65, d1: -0.5 },
      priority: 5,
    },
    {
      id: 'seher',
      title: 'DAS AUGE JENSEITS DES HORIZONTS',
      emoji: '👁️',
      color: '#9B7DB8',
      description: 'Du spürst, was kommt – lange bevor andere es sehen.',
      thresholds: { d3: -0.45, d1: -0.5 },
      priority: 6,
    },
  ],
  resultMapping: {
    markerId: 'quiz.rpg_identity.v1',
    profileToTraits: {
      paladin: { 'marker.leadership.guardian': 0.80, 'marker.social.protective': 0.70 },
      berserker: { 'marker.instinct.primal_force': 0.90, 'marker.freedom.independence': 0.60 },
      heiler: { 'marker.emotion.empathy': 0.85, 'marker.spiritual.healing': 0.70 },
      nekromant: { 'marker.cognition.shadow_work': 0.80, 'marker.spiritual.depth': 0.75 },
      stratege: { 'marker.cognition.system_thinking': 0.85, 'marker.leadership.planner': 0.70 },
      seher: { 'marker.instinct.gut_feeling': 0.80, 'marker.spiritual.vision': 0.75 },
    },
  },
};
