import type { QuizDefinition } from '../schema';

export const socialRoleQuiz: QuizDefinition = {
  id: 'quiz.social_role.v2',
  title: 'Your Social Role',
  titleDe: 'Deine Soziale Rolle',
  subtitle: 'What function do you fulfill in groups?',
  subtitleDe: 'Welche Funktion erf\u00fcllst du in Gruppen?',
  emoji: '\ud83c\udfad',
  accentColor: '#D4AF37',
  scoringModel: 'categorical',
  dimensions: ['leadership', 'harmony', 'expression', 'support'],
  questions: [
    {
      id: 'q1',
      text: 'Wie verh\u00e4ltst du dich?',
      context: 'Eine Gruppe muss entscheiden, wohin es geht...',
      options: [
        { id: 'q1_a', text: 'Ich mache einen klaren Vorschlag', scores: { leadership: 5, expression: 3 } },
        { id: 'q1_b', text: 'Ich frage, was alle wollen', scores: { harmony: 5, support: 3 } },
        { id: 'q1_c', text: 'Ich mache einen Witz und lockere die Stimmung', scores: { expression: 5, harmony: 2 } },
        { id: 'q1_d', text: 'Ich beobachte erstmal, was die anderen denken', scores: { support: 2, harmony: 2 } },
      ],
    },
    {
      id: 'q2',
      text: 'Deine nat\u00fcrliche Reaktion?',
      context: 'Jemand in der Gruppe wirkt traurig...',
      options: [
        { id: 'q2_a', text: 'Ich spreche die Person direkt und einf\u00fchlsam an', scores: { support: 5, harmony: 4 } },
        { id: 'q2_b', text: 'Ich versuche, sie aufzuheitern', scores: { expression: 4, support: 3 } },
        { id: 'q2_c', text: 'Ich schaffe Raum, falls sie reden m\u00f6chte', scores: { harmony: 4, support: 4 } },
        { id: 'q2_d', text: 'Ich nehme es wahr, aber warte ab', scores: { leadership: 1, harmony: 2 } },
      ],
    },
    {
      id: 'q3',
      text: 'Wie reagierst du?',
      context: 'Die Stimmung kippt \u2013 es gibt Streit...',
      options: [
        { id: 'q3_a', text: 'Ich greife ein und moderiere', scores: { leadership: 5, harmony: 4 } },
        { id: 'q3_b', text: 'Ich versuche, die Wogen zu gl\u00e4tten', scores: { harmony: 5, support: 3 } },
        { id: 'q3_c', text: 'Ich mische mich nicht ein \u2013 nicht mein Kampf', scores: { expression: 1, leadership: 0 } },
        { id: 'q3_d', text: 'Ich unterst\u00fctze, wen ich f\u00fcr im Recht halte', scores: { leadership: 3, expression: 2 } },
      ],
    },
    {
      id: 'q4',
      text: 'Was beschreibt dich am besten?',
      context: 'Auf einer Party bist du...',
      options: [
        { id: 'q4_a', text: 'Der, der die Leute zusammenbringt', scores: { harmony: 5, leadership: 3 } },
        { id: 'q4_b', text: 'Der, der alle zum Lachen bringt', scores: { expression: 5, harmony: 2 } },
        { id: 'q4_c', text: 'Der, der tiefe Gespr\u00e4che f\u00fchrt', scores: { support: 4, harmony: 3 } },
        { id: 'q4_d', text: 'Der, der organisiert, dass alles l\u00e4uft', scores: { leadership: 5, support: 2 } },
      ],
    },
    {
      id: 'q5',
      text: 'Welche Rolle \u00fcbernimmst du automatisch?',
      context: 'In einem Team-Projekt...',
      options: [
        { id: 'q5_a', text: 'Der mit dem Plan \u2013 ich strukturiere', scores: { leadership: 5, support: 2 } },
        { id: 'q5_b', text: 'Der Motivator \u2013 ich halte die Stimmung hoch', scores: { expression: 4, harmony: 4 } },
        { id: 'q5_c', text: 'Der Zuh\u00f6rer \u2013 ich sammle alle Meinungen', scores: { harmony: 5, support: 4 } },
        { id: 'q5_d', text: 'Der Macher \u2013 ich setze um', scores: { leadership: 3, expression: 2 } },
      ],
    },
    {
      id: 'q6',
      text: 'Wie gehst du damit um?',
      context: 'Du hast eine unpopul\u00e4re Meinung...',
      options: [
        { id: 'q6_a', text: 'Ich sage sie trotzdem \u2013 Ehrlichkeit z\u00e4hlt', scores: { leadership: 4, expression: 4 } },
        { id: 'q6_b', text: 'Ich warte auf den richtigen Moment', scores: { harmony: 3, leadership: 2 } },
        { id: 'q6_c', text: 'Ich verpacke sie humorvoll', scores: { expression: 5, harmony: 3 } },
        { id: 'q6_d', text: 'Ich behalte sie f\u00fcr mich \u2013 Frieden ist wichtiger', scores: { harmony: 5, support: 2 } },
      ],
    },
    {
      id: 'q7',
      text: 'Wie hilfst du?',
      context: 'Ein Freund braucht einen Rat...',
      options: [
        { id: 'q7_a', text: 'Ich h\u00f6re zu und stelle Fragen', scores: { support: 5, harmony: 4 } },
        { id: 'q7_b', text: 'Ich sage klar, was ich denke', scores: { leadership: 4, expression: 3 } },
        { id: 'q7_c', text: 'Ich teile \u00e4hnliche Erfahrungen', scores: { harmony: 4, expression: 3 } },
        { id: 'q7_d', text: 'Ich lenke ab, um den Kopf freizubekommen', scores: { expression: 4, support: 2 } },
      ],
    },
    {
      id: 'q8',
      text: 'Wie findest du deinen Platz?',
      context: 'Du kommst in eine neue Gruppe...',
      options: [
        { id: 'q8_a', text: 'Ich beobachte und passe mich an', scores: { harmony: 4, support: 3 } },
        { id: 'q8_b', text: 'Ich stelle mich vor und bringe mich ein', scores: { expression: 4, leadership: 4 } },
        { id: 'q8_c', text: 'Ich suche mir einen Gespr\u00e4chspartner', scores: { support: 4, harmony: 4 } },
        { id: 'q8_d', text: 'Ich schaue, wo ich helfen kann', scores: { support: 5, harmony: 3 } },
      ],
    },
    {
      id: 'q9',
      text: 'Was ist dein Impuls?',
      context: 'Die Gruppe ist ratlos...',
      options: [
        { id: 'q9_a', text: 'Ich \u00fcbernehme und gebe Richtung vor', scores: { leadership: 5, expression: 3 } },
        { id: 'q9_b', text: 'Ich sammle Ideen von allen', scores: { harmony: 5, support: 4 } },
        { id: 'q9_c', text: 'Ich mache einen unkonventionellen Vorschlag', scores: { expression: 5, leadership: 2 } },
        { id: 'q9_d', text: 'Ich unterst\u00fctze, wer sich traut', scores: { support: 5, harmony: 3 } },
      ],
    },
    {
      id: 'q10',
      text: 'W\u00e4hle deine Superpower:',
      context: 'Was macht dich in Gruppen wertvoll?',
      options: [
        { id: 'q10_a', text: 'Ich bringe Struktur und Klarheit', scores: { leadership: 5, harmony: 2 } },
        { id: 'q10_b', text: 'Ich verbinde Menschen miteinander', scores: { harmony: 5, support: 4 } },
        { id: 'q10_c', text: 'Ich bringe Energie und gute Laune', scores: { expression: 5, harmony: 3 } },
        { id: 'q10_d', text: 'Ich sorge daf\u00fcr, dass sich alle wohlf\u00fchlen', scores: { support: 5, harmony: 4 } },
      ],
    },
  ],
  profiles: [
    {
      id: 'leader',
      title: 'Der Anf\u00fchrer',
      emoji: '\ud83d\udc51',
      color: '#D4AF37',
      description: 'Du bist der nat\u00fcrliche Pol, um den sich Gruppen ordnen. Nicht weil du dich aufdr\u00e4ngst, sondern weil andere in dir die Klarheit finden, die sie suchen. Du triffst Entscheidungen, wenn alle anderen noch diskutieren.',
      minScore: 0,
      priority: 1,
    },
    {
      id: 'connector',
      title: 'Der Br\u00fcckenbauer',
      emoji: '\ud83c\udf09',
      color: '#8FB8A8',
      description: 'Du bist der soziale Klebstoff. Du merkst, wer sich unwohl f\u00fchlt, wer ausgegrenzt wird, und du baust Br\u00fccken. Ohne dich w\u00fcrden Gruppen in Einzelteile zerfallen.',
      minScore: 0,
      priority: 2,
    },
    {
      id: 'entertainer',
      title: 'Der Entertainer',
      emoji: '\ud83c\udfad',
      color: '#E8C87A',
      description: 'Du bist die Energie im Raum. Du sp\u00fcrst, wann die Stimmung kippt, und du wei\u00dft, wie du sie drehst. Dein Humor ist keine Flucht \u2013 er ist Medizin f\u00fcr die Seele der Gruppe.',
      minScore: 0,
      priority: 3,
    },
    {
      id: 'sage',
      title: 'Der Weise',
      emoji: '\ud83d\udcda',
      color: '#5B8A9A',
      description: 'Du bist der ruhende Pol. W\u00e4hrend andere reagieren, beobachtest du. Und wenn du sprichst, h\u00f6ren alle zu \u2013 weil sie wissen, dass deine Worte Gewicht haben.',
      minScore: 0,
      priority: 4,
    },
    {
      id: 'caretaker',
      title: 'Der H\u00fcter',
      emoji: '\ud83d\udee1\ufe0f',
      color: '#1C5B5C',
      description: 'Du bist das Herz der Gruppe. Du merkst, wer Hunger hat, wer m\u00fcde ist, wer Unterst\u00fctzung braucht. Deine F\u00fcrsorge ist keine Schw\u00e4che \u2013 sie ist die Grundlage, auf der alles andere gedeiht.',
      minScore: 0,
      priority: 5,
    },
    {
      id: 'rebel',
      title: 'Der Rebell',
      emoji: '\ud83d\udd25',
      color: '#C45D4A',
      description: 'Du bist der notwendige St\u00f6rfaktor. Du sagst, was andere denken, aber nicht aussprechen. Gruppen brauchen dich \u2013 auch wenn sie es nicht immer zugeben.',
      minScore: 0,
      priority: 6,
    },
  ],
  resultMapping: {
    markerId: 'quiz.social_role.v2',
    profileToTraits: {},
  },
};
