import type { QuizDefinition } from '../schema';

export const spotlightQuiz: QuizDefinition = {
  id: 'quiz.spotlight.v2',
  title: 'The Spotlight',
  titleDe: 'Das Rampenlicht',
  subtitle: 'How much attention do you really need?',
  subtitleDe: 'Wie viel Aufmerksamkeit brauchst du wirklich?',
  emoji: '\u2728',
  accentColor: '#D4AF37',
  scoringModel: 'categorical',
  dimensions: ['natural_star', 'active_shaper', 'situational_performer', 'selective_sharer', 'silent_observer'],
  questions: [
    {
      id: 'sq1',
      text: 'Dein erster Impuls?',
      context: 'Du betrittst einen vollen Raum...',
      options: [
        { id: 'sq1a', text: 'Ich suche bekannte Gesichter', scores: { selective_sharer: 5, situational_performer: 3 } },
        { id: 'sq1b', text: 'Ich stelle mich an den Rand und beobachte', scores: { silent_observer: 5, selective_sharer: 3 } },
        { id: 'sq1c', text: 'Ich mache mich bemerkbar', scores: { natural_star: 5, active_shaper: 3 } },
        { id: 'sq1d', text: 'Ich gehe direkt auf neue Leute zu', scores: { active_shaper: 5, situational_performer: 3 } },
      ],
    },
    {
      id: 'sq2',
      text: 'Wo stehst du?',
      context: 'Ein Foto wird gemacht...',
      options: [
        { id: 'sq2a', text: 'In der Mitte, gerne vorne', scores: { natural_star: 5, active_shaper: 3 } },
        { id: 'sq2b', text: 'Irgendwo im Hintergrund', scores: { silent_observer: 5, selective_sharer: 3 } },
        { id: 'sq2c', text: 'Dort, wo Platz ist', scores: { situational_performer: 5, active_shaper: 2 } },
        { id: 'sq2d', text: 'Lieber hinter der Kamera', scores: { silent_observer: 5, selective_sharer: 4 } },
      ],
    },
    {
      id: 'sq3',
      text: 'Wie oft postest du?',
      context: 'Social Media...',
      options: [
        { id: 'sq3a', text: 'T\u00e4glich, mein Leben ist Content', scores: { natural_star: 5, active_shaper: 3 } },
        { id: 'sq3b', text: 'Selten, nur besondere Momente', scores: { selective_sharer: 5, situational_performer: 3 } },
        { id: 'sq3c', text: 'Nie, ich schaue nur', scores: { silent_observer: 5, selective_sharer: 2 } },
        { id: 'sq3d', text: 'Wenn ich etwas Wichtiges zu sagen habe', scores: { active_shaper: 5, situational_performer: 3 } },
      ],
    },
    {
      id: 'sq4',
      text: 'Singst du?',
      context: 'Karaoke Abend...',
      options: [
        { id: 'sq4a', text: 'Ja! Gebt mir das Mikrofon!', scores: { natural_star: 5, active_shaper: 4 } },
        { id: 'sq4b', text: 'Nur in der Gruppe', scores: { situational_performer: 5, selective_sharer: 3 } },
        { id: 'sq4c', text: 'Niemals, keine Chance', scores: { silent_observer: 5, selective_sharer: 3 } },
        { id: 'sq4d', text: 'Vielleicht sp\u00e4ter, wenn die Stimmung passt', scores: { selective_sharer: 5, situational_performer: 3 } },
      ],
    },
    {
      id: 'sq5',
      text: 'Was tr\u00e4gst du?',
      context: 'Kleidungsstil...',
      options: [
        { id: 'sq5a', text: 'Auff\u00e4llig, ich will gesehen werden', scores: { natural_star: 5, active_shaper: 3 } },
        { id: 'sq5b', text: 'Praktisch und bequem', scores: { silent_observer: 5, situational_performer: 2 } },
        { id: 'sq5c', text: 'Stilvoll, aber dezent', scores: { selective_sharer: 5, situational_performer: 3 } },
        { id: 'sq5d', text: 'Statement-Pieces', scores: { active_shaper: 5, natural_star: 3 } },
      ],
    },
    {
      id: 'sq6',
      text: 'Wie f\u00fchlst du dich?',
      context: 'Ein Fehler passiert \u00f6ffentlich...',
      options: [
        { id: 'sq6a', text: 'Ich lache dar\u00fcber und mache weiter', scores: { natural_star: 5, active_shaper: 4 } },
        { id: 'sq6b', text: 'Ich stehe dazu und erkl\u00e4re es', scores: { active_shaper: 5, situational_performer: 3 } },
        { id: 'sq6c', text: 'Mir ist es extrem unangenehm', scores: { silent_observer: 5, selective_sharer: 4 } },
        { id: 'sq6d', text: 'Ich hoffe, niemand hat es gemerkt', scores: { selective_sharer: 5, situational_performer: 2 } },
      ],
    },
    {
      id: 'sq7',
      text: 'Magst du das?',
      context: 'Lob vor der Gruppe...',
      options: [
        { id: 'sq7a', text: 'Ja, Applaus tut gut!', scores: { natural_star: 5, active_shaper: 4 } },
        { id: 'sq7b', text: 'Ein kurzes Danke reicht', scores: { situational_performer: 5, selective_sharer: 3 } },
        { id: 'sq7c', text: 'Bitte nicht, lieber unter vier Augen', scores: { silent_observer: 5, selective_sharer: 4 } },
        { id: 'sq7d', text: 'Wenn es gerechtfertigt ist, okay', scores: { active_shaper: 5, situational_performer: 3 } },
      ],
    },
    {
      id: 'sq8',
      text: 'Was tust du?',
      context: 'Du wirst unterbrochen...',
      options: [
        { id: 'sq8a', text: 'Ich werde lauter und rede weiter', scores: { natural_star: 5, active_shaper: 4 } },
        { id: 'sq8b', text: 'Ich lasse den anderen reden', scores: { silent_observer: 5, selective_sharer: 3 } },
        { id: 'sq8c', text: 'Ich weise h\u00f6flich darauf hin', scores: { active_shaper: 5, situational_performer: 3 } },
        { id: 'sq8d', text: 'Ich warte eine Pause ab', scores: { selective_sharer: 5, situational_performer: 3 } },
      ],
    },
  ],
  profiles: [
    {
      id: 'natural_star',
      title: 'Der Natural Star',
      emoji: '\ud83c\udf1f',
      color: '#D4AF37',
      description: 'Du brauchst keine Scheinwerfer, du leuchtest von selbst. Aufmerksamkeit ist f\u00fcr dich Energie. Du hast keine Angst davor, gesehen zu werden \u2013 im Gegenteil, du bl\u00fchst auf, wenn alle Augen auf dich gerichtet sind. Dein Charisma ist magnetisch.',
      minScore: 0,
      priority: 1,
    },
    {
      id: 'active_shaper',
      title: 'Der Gestalter',
      emoji: '\ud83d\udde3\ufe0f',
      color: '#8FB8A8',
      description: 'Du suchst das Rampenlicht nicht um seiner selbst willen, sondern um etwas zu bewegen. Wenn du sprichst, dann weil du etwas zu sagen hast. Du kannst f\u00fchren und pr\u00e4sentieren, brauchst aber auch Pausen vom Trubel.',
      minScore: 0,
      priority: 2,
    },
    {
      id: 'situational_performer',
      title: 'Der Situative',
      emoji: '\ud83c\udfad',
      color: '#5B8A9A',
      description: 'Du dr\u00e4ngst dich nicht auf, aber du versteckst dich auch nicht. Du passt dich der Situation an. Du kannst charmant und unterhaltsam sein, genie\u00dft aber auch die Ruhe. Du bist der perfekte Teamplayer.',
      minScore: 0,
      priority: 3,
    },
    {
      id: 'selective_sharer',
      title: 'Der Selektive',
      emoji: '\ud83d\udd10',
      color: '#E8C87A',
      description: 'Du bist w\u00e4hlerisch, wem du deine Energie schenkst. Du \u00f6ffnest dich nicht jedem, aber wenn, dann tief. Oberfl\u00e4chlichkeit langweilt dich. Du wirst vielleicht oft untersch\u00e4tzt, weil du nicht laut bist.',
      minScore: 0,
      priority: 4,
    },
    {
      id: 'silent_observer',
      title: 'Der Beobachter',
      emoji: '\ud83d\udc40',
      color: '#1C5B5C',
      description: 'Du meidest das Rampenlicht wie der Teufel das Weihwasser. Deine St\u00e4rke liegt in der Analyse und Beobachtung. Du bist der Stratege im Hintergrund, der die F\u00e4den zieht oder einfach nur seine Ruhe genie\u00dft.',
      minScore: 0,
      priority: 5,
    },
  ],
  resultMapping: {
    markerId: 'quiz.spotlight.v2',
    profileToTraits: {},
  },
};
