/**
 * KohaerenzHero — Central coherence index display.
 *
 * The first content block the user sees after the page header.
 * Shows the harmonyIndex as a percentage ring, a neutral framing label,
 * and a driver strip explaining what inputs shape the current value.
 *
 * Architecture decision (2026-04-12):
 * - The numeric value is math-derived (computeDayHarmonic).
 * - Semantic interpretation (label text) belongs in the LLM layer (FuFirE API).
 * - Client-side labels are neutral fallbacks only — no semantic loading.
 * - When FuFirE returns coherence_label, display that instead.
 *
 * Implements: docs/wireframes/dashboard-mockup-revision-coherence-first.md §1–§2
 */

import { useMemo } from 'react';
import { useLanguage } from '../../contexts/LanguageContext';
import type { DayHarmonicState } from '../../lib/fusion-ring/day-harmonic';
import type { SpaceWeatherState } from '../../hooks/useSpaceWeather';
import type { TransitEvent } from '../../lib/schemas/transit-state';

// ── Types ────────────────────────────────────────────────────────────────────

export interface KohaerenzHeroProps {
  /** 0–1 harmonyIndex, mode, intensity from activeDayHarmonic */
  dayHarmonic: DayHarmonicState | null;
  /** Cosmic weather state — Kp, solar pressure, gScale */
  spaceWeather: SpaceWeatherState;
  /** Transit events for driver context */
  transitEvents: TransitEvent[];
  /** 'pulse' = active day; 'trace' = reflective day */
  dayMode: 'pulse' | 'trace';
  /** True while data is loading */
  loading: boolean;
  /** 0–100 from POST /api/impact/active — primary source when available (REQ-F-coherence-hero-impact-datasource) */
  impactHarmonyIndex?: number | null;
  /** True while the Impact endpoint is loading */
  impactLoading?: boolean;
}

// ── Coherence Ring ───────────────────────────────────────────────────────────

function CoherenceRing({ value, size = 120 }: { value: number; size?: number }) {
  const radius = (size - 12) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference * (1 - value);

  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        {/* Track */}
        <circle
          cx={size / 2} cy={size / 2} r={radius}
          fill="none" strokeWidth={6}
          stroke="var(--tile-border)"
        />
        {/* Fill */}
        <circle
          cx={size / 2} cy={size / 2} r={radius}
          fill="none" strokeWidth={6}
          stroke="var(--tile-accent)"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          style={{ transition: 'stroke-dashoffset 1s ease-out' }}
        />
      </svg>
      <div className="absolute inset-0 flex items-center justify-center">
        <span className="font-serif text-3xl" style={{ color: 'var(--tile-text-primary)' }}>
          {Math.round(value * 100)}
        </span>
      </div>
    </div>
  );
}

// ── Neutral fallback labels ──────────────────────────────────────────────────
// Describes the mathematical state, not its meaning.
// Semantic interpretation is generated by the LLM layer in FuFirE.

function getCoherenceFallbackLabel(
  h: number,
  lang: 'de' | 'en',
): { title: string; subtitle: string } {
  if (h >= 0.70) return lang === 'de'
    ? { title: 'Hohe Übereinstimmung', subtitle: 'Himmel und Signatur liegen nah beieinander' }
    : { title: 'High alignment', subtitle: 'Sky and signature are closely aligned' };
  if (h >= 0.40) return lang === 'de'
    ? { title: 'Mittlere Übereinstimmung', subtitle: 'Teils im Einklang, teils in Spannung' }
    : { title: 'Moderate alignment', subtitle: 'Partly in harmony, partly in tension' };
  return lang === 'de'
    ? { title: 'Niedrige Übereinstimmung', subtitle: 'Himmel und Signatur stehen in Distanz' }
    : { title: 'Low alignment', subtitle: 'Sky and signature are at distance' };
}

// ── Driver Strip ─────────────────────────────────────────────────────────────

type DriverState = 'calm' | 'active' | 'tense';

interface DriverPill {
  label: string;
  value: string;
  state: DriverState;
}

const STATE_CLASSES: Record<DriverState, string> = {
  calm:   'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  active: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  tense:  'bg-red-500/10 text-red-400 border-red-500/20',
};

function classifyKp(kp: number): DriverState {
  if (kp <= 2) return 'calm';
  if (kp <= 4) return 'active';
  return 'tense';
}

function classifySolarPressure(sp: number): DriverState {
  if (sp < 0.3) return 'calm';
  if (sp <= 0.6) return 'active';
  return 'tense';
}

function classifyTransitCount(count: number): DriverState {
  if (count <= 1) return 'calm';
  if (count <= 3) return 'active';
  return 'tense';
}

function buildDrivers(
  spaceWeather: SpaceWeatherState,
  transitEvents: TransitEvent[],
  dayMode: 'pulse' | 'trace',
  lang: 'de' | 'en',
): DriverPill[] {
  const isDe = lang === 'de';

  return [
    {
      label: isDe ? 'Geomagnetik' : 'Geomagnetic',
      value: `Kp ${spaceWeather.kpIndex}`,
      state: classifyKp(spaceWeather.kpIndex),
    },
    {
      label: isDe ? 'Solardruck' : 'Solar pressure',
      value: `${Math.round(spaceWeather.solarPressure * 100)}%`,
      state: classifySolarPressure(spaceWeather.solarPressure),
    },
    {
      label: isDe ? 'Transit-Aktivität' : 'Transit activity',
      value: `${transitEvents.length} ${isDe ? 'aktiv' : 'active'}`,
      state: classifyTransitCount(transitEvents.length),
    },
    {
      label: isDe ? 'Tagesfeld' : 'Day field',
      value: dayMode === 'pulse'
        ? (isDe ? 'Impuls' : 'Pulse')
        : (isDe ? 'Spur' : 'Trace'),
      state: dayMode === 'pulse' ? 'calm' : 'active',
    },
  ];
}

// ── Skeleton ─────────────────────────────────────────────────────────────────

function KohaerenzHeroSkeleton() {
  return (
    <div className="cosmic-tile p-6 sm:p-8 rounded-[2rem] animate-pulse">
      <div className="flex items-center gap-8">
        <div className="w-[120px] h-[120px] rounded-full bg-white/5" />
        <div className="flex-1 space-y-3">
          <div className="h-3 w-24 rounded bg-white/10" />
          <div className="h-6 w-48 rounded bg-white/10" />
          <div className="h-3 w-64 rounded bg-white/10" />
        </div>
      </div>
      <div className="flex gap-2 mt-6">
        {[1, 2, 3, 4].map((i) => (
          <div key={i} className="h-8 flex-1 rounded-lg bg-white/5" />
        ))}
      </div>
    </div>
  );
}

// ── Component ────────────────────────────────────────────────────────────────

export function KohaerenzHero({
  dayHarmonic,
  spaceWeather,
  transitEvents,
  dayMode,
  loading,
  impactHarmonyIndex,
  impactLoading,
}: KohaerenzHeroProps) {
  const { lang } = useLanguage();
  const resolvedLang: 'de' | 'en' = lang === 'de' ? 'de' : 'en';

  const drivers = useMemo(
    () => buildDrivers(spaceWeather, transitEvents, dayMode, resolvedLang),
    [spaceWeather, transitEvents, dayMode, resolvedLang],
  );

  const isLoading = (loading && !dayHarmonic) || (impactLoading && impactHarmonyIndex == null);
  if (isLoading) {
    return <KohaerenzHeroSkeleton />;
  }

  // Primary: Impact API harmony_index (0–100, server-side, includes solar pressure).
  // Fallback: dayHarmonic.harmonyIndex (0–1, client-side, Wu-Xing cosine only).
  const harmonyValue = impactHarmonyIndex != null
    ? impactHarmonyIndex / 100
    : (dayHarmonic?.harmonyIndex ?? 0);
  const label = getCoherenceFallbackLabel(harmonyValue, resolvedLang);

  return (
    <div className="kohaerenz-hero cosmic-tile p-6 sm:p-8 rounded-[2rem]">
      {/* ── Score + Label ─────────────────────────────────── */}
      <div className="flex items-center gap-6 sm:gap-8">
        <CoherenceRing value={harmonyValue} />

        <div className="flex-1 min-w-0 space-y-1">
          <p
            className="text-[9px] font-sans uppercase tracking-[0.3em]"
            style={{ color: 'var(--tile-accent)', opacity: 0.6 }}
          >
            Kohärenzindex
          </p>
          <h2
            className="font-serif text-xl sm:text-2xl leading-tight truncate"
            style={{ color: 'var(--tile-text-primary)' }}
          >
            {label.title}
          </h2>
          <p
            className="text-xs leading-relaxed"
            style={{ color: 'var(--tile-text-secondary)', opacity: 0.7 }}
          >
            {label.subtitle}
          </p>
        </div>
      </div>

      {/* ── Driver Strip ──────────────────────────────────── */}
      <div className="flex flex-wrap gap-2 mt-5 pt-4 border-t" style={{ borderColor: 'var(--tile-border)' }}>
        {drivers.map((driver) => (
          <div
            key={driver.label}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-[10px] font-mono ${STATE_CLASSES[driver.state]}`}
          >
            <span className="opacity-70">{driver.label}</span>
            <span className="font-semibold">{driver.value}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
